# Intro python data science
## Práctica 03: Paquetes

Vamos a ver:
* Punto 1: Qué son los paquetes y su uso
* Punto 2: Diferencias entre funciones y métodos
* Punto 3: Paquetes básicos en ciencia de datos

# Punto 1:

In [1]:
# Cómo importar un paquete
import numpy

In [2]:
numpy.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
# Cómo importar un paquete con acrónimo
import numpy as np

In [4]:
# objeto array de numpy
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Cómo cargar una función específica de un paquete

In [5]:
from numpy import arange

In [6]:
arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# Punto 2:

In [ ]:
# Diferencias entre funciones y métodos

In [7]:
A=np.arange(9)

In [8]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
# que tipo de objeto es A
type(A)

numpy.ndarray

In [10]:
# calculando promedio con función de numpy
np.mean(A)

4.0

In [11]:
# calculando promedio con método de objeto
A.mean()

4.0

In [ ]:
# Haciendo un reshape con funciones y métodos

In [12]:
# transformando arreglo con función de numpy
np.reshape(A, (3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
# transformando arreglo con método de objeto
A.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
A.metodo1().metodo2().metodo3()

# Gracias!
## Espero que te lleves algo útil de este notebook 😀

Para más videos de programación para ciencia de datos

https://www.youtube.com/c/RafaGonzalezGouveia/

Si quieres realizar alguno de los cursos online de pago, ve a:

https://cursos.gonzalezgouveia.com