# Intro python data science
## Práctica 04: numpy ndarray

Vamos a ver cómo:
* Punto 1: Crear ndarrays en python
* Punto 2: Operar entre columnas
* Punto 3: Seleccionar elementos

# Punto 1:

In [1]:
# importar numpy
import numpy as np

In [105]:
# crear lista con numeros primos
numeros_primos=[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
numeros_primos

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

In [106]:
# crear array a partir de lista
array_primos=np.array(numeros_primos)
array_primos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [181]:
# crear arrays con ceros o cómo inicializar un arreglo de numpy
array_zeros=np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [81]:
# crear arrays con números
array_numeros=np.arange(10)
array_numeros

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [177]:
# array con numeros sucesivos
array_pares=np.arange(0, 20, 2)
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [182]:
# haciendo un reshape para dos dimensiones
array_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

# Punto 2:

In [109]:
# operaciones aritmeticas sobre np array 1-dimension y 2-dimension
array_impares = array_pares + 1
array_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [120]:
# multiplicar por 100
array_impares*100

array([ 100,  300,  500,  700,  900, 1100, 1300, 1500, 1700, 1900])

In [119]:
# resta entre arrays
array_impares - array_pares

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [180]:
# cuidado con la división entre cero
array_primos/array_pares

C:\Users\raf_v\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.5       , 1.25      , 1.16666667, 1.375     ,
       1.3       , 1.41666667, 1.35714286, 1.4375    , 1.61111111])

In [127]:
# métodos asociados a estadística
# suma
array_primos.sum()

129

In [129]:
# promedio
array_primos.mean()

12.9

In [130]:
# varianza
array_primos.var()

73.28999999999999

In [215]:
# como ordenar un np array
array_fibonacci = np.array([55, 0, 144, 1, 21, 89, 5, 8, 13, 1, 34, 3, 2])
array_fibonacci

array([ 55,   0, 144,   1,  21,  89,   5,   8,  13,   1,  34,   3,   2])

In [216]:
# orden ascendente: de menor a mayor
np.sort(array_fibonacci)

array([  0,   1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144])

In [217]:
# orden descendente: de mayor a menor
-np.sort(-array_fibonacci)

array([144,  89,  55,  34,  21,  13,   8,   5,   3,   2,   1,   1,   0])

# Punto 3:

In [218]:
# Como seleccionar elements

In [219]:
# Seleccionar un elemento

In [220]:
A = np.arange(0,20,2).reshape(2,5)
A

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [221]:
# seleccionar el primer elemento
A[0,0]

0

In [222]:
# seleccionar algún otro elemento
A[1,3]

16

In [223]:
# Seleccionar varios elementos

In [224]:
# seleccionar por fila
A[1,:]

array([10, 12, 14, 16, 18])

In [225]:
# seleccionar por columna
A[:,3]

array([ 6, 16])

In [226]:
# Utilizar filter

In [227]:
array_fibonacci

array([ 55,   0, 144,   1,  21,  89,   5,   8,  13,   1,  34,   3,   2])

In [228]:
# conidicion para menores de 20
array_fibonacci < 20

array([False,  True, False,  True, False, False,  True,  True,  True,
        True, False,  True,  True])

In [231]:
# filtrar menores de 20
array_fibonacci[array_fibonacci < 20]

array([ 0,  1,  5,  8, 13,  1,  3,  2])

# Gracias!
## Espero que te lleves algo útil de este notebook 😀

Para más videos de programación para ciencia de datos

https://www.youtube.com/c/RafaGonzalezGouveia/

Si quieres realizar alguno de los cursos online de pago, ve a:

https://cursos.gonzalezgouveia.com